global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

entryPoints:
  # Not used in apps, but redirect everything from HTTP to HTTPS
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  # HTTPS endpoint, with domain wildcard
  https:
    address: :443

providers:
  providersThrottleDuration: 2s

  file:
    filename: /etc/traefik/config/nextcloud.yml
    watch: true

  # Docker provider for connecting all apps that are inside of the docker network
  # NOT USED BUT YOU CAN ADAPT ;) 
  docker:
    watch: true
    network: traefik_network # Add Your Docker Network Name Here
    # Default host rule to containername.domain.example
    defaultRule: 'Host(`{{ index .Labels "com.docker.compose.service"}}.YOURDOMAIN.COM`)'
    swarmModeRefreshSeconds: 15s
    exposedByDefault: false

api:
  dashboard: true
  insecure: true

log:
  level: INFO

certificatesResolvers:
  staging:
    acme:
      email: <email>
      storage: /ssl-certs/acme-staging.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      tlsChallenge: {}

  production:
    acme:
      email: <email>
      storage: /ssl-certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      tlsChallenge: {}
